name: "Build & Upload Package"

on:
  workflow_dispatch:

jobs:
  build_upload:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - shell: bash
          run: bash step1.sh

        - shell: bash
          run: bash step2.sh

        - name: Upload archive to release
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "ComfyUI_Windows_portable_cu121.7z*"
            # always draft before release
            draft: true
            overwrite: true
