name: "Assembling package"

on:
  workflow_dispatch:

jobs:
  package_comfyui:
    permissions:
        contents: "write"
        packages: "write"
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/cache/restore@v4
          id: cache
          with:
            path: |
              python_embeded
            key: Windows-cp311-cu121

        - shell: bash
          run: bash step2.sh

        - name: Upload archive to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.REPO_TOKEN }}
            file: ComfyUI_Windows_portable_cu121.7z
            tag: "latest"
            overwrite: true
