name: "Gathering dependencies"

on:
  workflow_dispatch:

jobs:
  build_dependencies:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: 3.11.8

        - shell: bash
          run: bash step1.sh

        - uses: actions/cache/save@v4
          with:
            path: |
              python_embeded
            key: Windows-cp311-cu121
