name: "Assembling package"

on:
  workflow_dispatch:

jobs:
  package_comfyui:
    permissions:
        contents: "write"
        packages: "write"
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/cache/restore@v4
          id: cache
          with:
            path: |
              python_embeded
            key: Windows-cp311-cu121

        - shell: bash
          run: bash step2.sh

        - name: Upload archive to release
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "ComfyUI_Windows_portable_cu121.7z*"
            # always draft before release
            draft: true
            # delete old files before uploading, in case multiple .7z.00X files overlap
            delete_file: "ComfyUI_Windows_portable*"
            overwrite: true
            update_latest_release: true
