name: "Assembling package"

on:
  workflow_dispatch:

jobs:
  package_comfyui:
    permissions:
        contents: "write"
        packages: "write"
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache/restore@v4
          id: cache
          with:
            path: |
              cp311_cu121_deps.tar
            key: Windows-build-cp311-cu121

        - shell: bash
          run: bash step2.sh

        - name: Upload binaries to release
          uses: softprops/action-gh-release@v2
          with:
            files: ComfyUI_Windows_portable_cu121.7z
